# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['gui_launcher.py'],
    pathex=['.', 'src'],
    binaries=[],
    datas=[
        ('audio',       'audio'),
        ('themes',      'themes'),
        ('config',      'config'),
        ('profiles',    'profiles'),
        ('version.json', '.'),
        ('app_icon.ico', '.'),
        ('Help.txt',    '.'),
        ('src',         'src'),
    ],
    hiddenimports=[
        # src modules
        'common',
        'shared_vars',
        'logger',
        'mp_types',
        'profiles',
        'updater',
        'theme_restart',
        'video_extractor',
        'roblox_uploader',
        'timeline_builder',
        'zstd_tool',
        'src.common',
        'src.shared_vars',
        'src.logger',
        'src.mp_types',
        'src.profiles',
        'src.updater',
        'src.theme_restart',
        'src.video_extractor',
        'src.roblox_uploader',
        'src.timeline_builder',
        'src.zstd_tool',
        # gui modules
        'src.gui.app_lifecycle',
        'src.gui.components',
        'src.gui.constants',
        'src.gui.dashboard_page',
        'src.gui.help_page',
        'src.gui.keyboard_handler',
        'src.gui.loader',
        'src.gui.log_handler',
        'src.gui.logs_page',
        'src.gui.settings_page',
        'src.gui.statistics_page',
        'src.gui.styles',
        'src.gui.themes',
        'src.gui.ui_updater',
        'src.gui.utils',
        'src.gui.animation_uploader_page',
        'src.gui.encoder_page',
        'src.gui.profiles_page',
        # third-party
        'cv2',
        'PIL',
        'PIL._tkinter_finder',
        'customtkinter',
        'keyboard',
        'requests',
        'zstandard',
        'multiprocessing',
        'multiprocessing.pool',
        'multiprocessing.managers',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['pkg_resources.py2_warn'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Nexuse',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app_icon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Nexuse',
)
