# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['gui_launcher.py'],
    pathex=['.', 'src'],
    binaries=[],
    datas=[
        ('pictures',    'pictures'),
        ('audio',       'audio'),
        ('themes',      'themes'),
        ('config',      'config'),
        ('profiles',    'profiles'),
        ('version.json', '.'),
        ('app_icon.ico', '.'),
        ('Help.txt',    '.'),
        ('src',         'src'),
    ],
    hiddenimports=[
        # src modules imported as bare names
        'mirror',
        'mirror_1366',
        'mirror_utils',
        'mirror_utils_1366',
        'common',
        'shared_vars',
        'core',
        'compiled_runner',
        'exp_runner',
        'threads_runner',
        'luxcavation_functions',
        'battler',
        'battlepass_collector',
        'extractor',
        'function_runner',
        'headless_bridge',
        'audio_manager',
        'logger',
        'movement_detector',
        'mp_types',
        'profiles',
        'updater',
        'Game_Launcher',
        'theme_restart',
        # src modules imported as src.*
        'src.mirror',
        'src.mirror_1366',
        'src.mirror_utils',
        'src.mirror_utils_1366',
        'src.common',
        'src.shared_vars',
        'src.core',
        'src.compiled_runner',
        'src.exp_runner',
        'src.threads_runner',
        'src.luxcavation_functions',
        'src.battler',
        'src.battlepass_collector',
        'src.extractor',
        'src.function_runner',
        'src.headless_bridge',
        'src.audio_manager',
        'src.logger',
        'src.movement_detector',
        'src.mp_types',
        'src.profiles',
        'src.updater',
        'src.Game_Launcher',
        'src.theme_restart',
        'src.gui.app_lifecycle',
        'src.gui.chain_automation',
        'src.gui.components',
        'src.gui.constants',
        'src.gui.dashboard_page',
        'src.gui.exp_page',
        'src.gui.help_page',
        'src.gui.keyboard_handler',
        'src.gui.loader',
        'src.gui.log_handler',
        'src.gui.logs_page',
        'src.gui.mirror_page',
        'src.gui.others_page',
        'src.gui.process_handler',
        'src.gui.schedule_page',
        'src.gui.scheduler_handler',
        'src.gui.settings_page',
        'src.gui.statistics_page',
        'src.gui.styles',
        'src.gui.themes',
        'src.gui.threads_page',
        'src.gui.ui_updater',
        'src.gui.utils',
        # third-party
        'interception',
        'interception._ioctl',
        'interception._keycodes',
        'interception._utils',
        'interception.beziercurve',
        'interception.constants',
        'interception.device',
        'interception.exceptions',
        'interception.inputs',
        'interception.interception',
        'interception.strokes',
        'pathgenerator',
        'cv2',
        'numpy',
        'mss',
        'mss.windows',
        'PIL',
        'PIL._tkinter_finder',
        'customtkinter',
        'keyboard',
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'multiprocessing',
        'multiprocessing.pool',
        'multiprocessing.managers',
        'requests',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['rthook_torch.py', 'rthook_loose_src.py'],
    excludes=['pkg_resources.py2_warn'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='WorkerBee',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app_icon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='WorkerBee',
)
