from multiprocessing import Value

class SharedVars:
    def __init__(self):
        self.x_offset = Value('i', 0)
        self.y_offset = Value('i', 0)
        self.game_monitor = Value('i', 1)
        self.skip_restshop = Value('b', False)
        self.skip_ego_check = Value('b', False)
        self.skip_ego_fusion = Value('b', False)
        self.skip_sinner_healing = Value('b', False)
        self.skip_ego_enhancing = Value('b', False)
        self.skip_ego_buying = Value('b', False)
        self.debug_image_matches = Value('b', False)
        self.hard_mode = Value('b', False)
        self.convert_images_to_grayscale = Value('b', True)
        self.reconnection_delay = Value('i', 6)
        self.reconnect_when_internet_reachable = Value('b', False)
        self.good_pc_mode = Value('b', True)
        self.click_delay = Value('f', 0.5)
        self.retry_count = Value('i', 0)
        self.claim_on_defeat = Value('b', False)
        self.pack_refreshes = Value('i', 7)
        self.exp_runs = Value('i', 1)
        self.exp_stage = Value('i', 6)
        self.threads_runs = Value('i', 3)
        self.threads_difficulty = Value('i', 4)
        self.stop_after_current_run = Value('b', False)
        self.convert_enkephalin_to_modules = Value('b', True)
        self.enable_animations = Value('b', True)
        self.audio_volume = Value('f', 0.5)